services:
  react:
    build: ./web
    container_name: react
    ports:
      - "5173:5173"
    restart: unless-stopped
    env_file:
      - ./web/.env
    networks:
      - nginx

  go:
    build: ./api
    container_name: go
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    restart: unless-stopped
    networks:
      - nginx
      - db
      - redis
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - redis

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: fysite
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

volumes:
  redis:
    driver: local
  db:

networks:
  nginx:
    name: nginx
    external: true
  redis:
    name: redis
  db:
    name: db
